# docker-compose.yml

version: '3'
#
services:
  fastapi:
    build: ./app
    container_name: "fastapi_container"
    volumes:
      - ./app:/app
    ports:
      - "5000:80"
#    depends_on:
#      - nginx
#
#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./certificate.crt:/path/to/certificate.crt
#      - ./private.key:/path/to/private.key
#    ports:
#      - "443:443"